import type { InputFieldConfig } from './types';

export const INPUT_FIELDS: InputFieldConfig[] = [
  {
    id: 'orbitalPeriod',
    label: 'Orbital Period',
    unit: 'days',
    tooltip: 'The time it takes for the planet to complete one orbit around its star.',
    defaultValue: 3553.21,
    step: 0.01,
    precision: 2,
  },
  {
    id: 'stellarRadius',
    label: 'Stellar Radius',
    unit: 'Solar radii',
    tooltip: 'The radius of the host star, measured in units of the Sun\'s radius.',
    defaultValue: 1.00,
    step: 0.01,
    precision: 2,
  },
  {
    id: 'planetRadius',
    label: 'Planet Radius',
    unit: 'Earth radii',
    tooltip: 'The radius of the planet, measured in units of Earth\'s radius.',
    defaultValue: 1.00,
    step: 0.01,
    precision: 2,
  },
  {
    id: 'stellarMass',
    label: 'Stellar Mass',
    unit: 'Solar masses',
    tooltip: 'The mass of the host star, measured in units of the Sun\'s mass.',
    defaultValue: 1.00,
    step: 0.01,
    precision: 2,
  },
  {
    id: 'equilibriumTemperature',
    label: 'Equilibrium Temperature',
    unit: 'K',
    tooltip: 'The theoretical temperature a planet would have if it were a black body heated only by its parent star.',
    defaultValue: 288.00,
    step: 1,
    precision: 2,
  },
  {
    id: 'stellarTemperature',
    label: 'Stellar Temperature',
    unit: 'K',
    tooltip: 'The surface temperature of the host star.',
    defaultValue: 5778.00,
    step: 1,
    precision: 2,
  },
  {
    id: 'insolationFlux',
    label: 'Insolation Flux',
    unit: 'Earth flux',
    tooltip: 'The amount of radiation received by the planet from its star, relative to Earth.',
    defaultValue: 1.00,
    step: 0.01,
    precision: 2,
  },
  {
    id: 'stellarAge',
    label: 'Stellar Age',
    unit: 'Gyr',
    tooltip: 'The age of the host star in billions of years (Giga-years).',
    defaultValue: 4.50,
    step: 0.01,
    precision: 2,
  },
  {
    id: 'distanceToStarRadius',
    label: 'Distance/Star Radius Ratio',
    unit: '',
    tooltip: 'The ratio of the semi-major axis of the planet\'s orbit to the stellar radius.',
    defaultValue: 215.00,
    step: 1,
    precision: 2,
  },
  {
    id: 'rightAscension',
    label: 'Right Ascension',
    unit: 'degrees',
    tooltip: 'The celestial equivalent of longitude.',
    defaultValue: 290.00,
    step: 1,
    precision: 2,
  },
  {
    id: 'declination',
    label: 'Declination',
    unit: 'degrees',
    tooltip: 'The celestial equivalent of latitude.',
    defaultValue: 42.00,
    step: 1,
    precision: 2,
  },
];